### ISSUE TITLE
background-image: radial-gradient causes high cpu usage on Safari

### ISSUE THREAD

**Issue by feeva** [framework7io/framework7#3394] opened 2019-11-13 09:13 UTC
* Framework7 version: 4, 5
* Platform and Target: iPhone 5, iPhone 8 Mobile apps and web pages

### Describe the bug
Following css line causes high cpu usage on iPhones so that they get warm or hot.

```
.md .navbar a.link:before {
    ...
    background-image: radial-gradient(circle at center, var(--f7-link-highlight-color) 66%, rgba(255, 255, 255, 0) 66%);
```

### To Reproduce
1. Just open a web page with Framework7 CSS on Safari 
2. Wait under a minute then the phone gets hot.

**Comment by feeva** [comment] 2019-11-13 09:15
Currently I solved this just by overriding the background-image.

Other than that, what's the point of radial-gradient? I don't see any gradient on the navbar links on Androids and web browsers.

**Comment by nolimits4web** [comment] 2019-11-14 08:22
Closing as duplicate of #2952

**Closed by nolimits4web** 2019-11-14 08:22 UTC
