### ISSUE TITLE
[v4] [less]  inline javaScript is deprecated / update to less 3.x

### ISSUE THREAD

**Issue by pi0** [framework7io/framework7#2285] opened 2018-03-19 22:38 UTC
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

Starting with less 3.0.0 Inline JavaScript is Deprecated in the flavor of plugins. ([Docs](http://lesscss.org/usage/#less-options-enable-inline-javascript-deprecated-))

It is currently being used for RTL variant. Example [list.less:196](https://github.com/framework7io/framework7/blob/master/src/components/list/list.less#L196)

BTW this is just an informational issue. Please close if there are no any plans using less 3 :D

**Comment by ZanderBrown** [comment] 2018-03-19 22:51
I'm not seeing inline js here ttps://github.com/framework7io/framework7/blob/fd17e7b1fe93e37049478a968e4fa55e85351a02/src/components/list/list.less#L196

**Comment by pi0** [comment] 2018-03-19 22:57
@ZanderBrown Unfortunately I can't reproduce the problem with this repository (gulp-less > less version 3.0.0 is not currently supported) but I think the object syntax is causing this problem...

**Comment by nolimits4web** [comment] 2018-03-20 06:50
Yes, i am aware of this when was trying to update gulp-less to v4 which uses less 3. But didn't find the solution and didn't get how to use that `plugin` options yet. So, temporary the project on less < 3

**Comment by fjorgemota** [comment] 2018-09-17 00:42
Hey.

I have sent a pull request to finally update Less and close this issue. On the process, I think the compatibility with up to Less 2.5 was maintaned, because I introduced a plugin to do the task that inline javascript (which was not being caused by `.ltr` declaration, but by the `.svg-background` mixin and a few others places) was doing.

I'm not sure if this could be merged on 3.x, because I did not tested on 2.5 (only tested on latest Less 3.x). But anyway feel free to review #2669. =)

Thanks.

**Closed** 2018-09-19 15:55 UTC
Labels: Feature Request
