### ISSUE TITLE
Back Navigation issue with Query Params

### ISSUE THREAD

**Issue by codetrash** [framework7io/framework7#1903] opened 2017-10-19 05:10 UTC
I have issue with Back navigation if I query params like this
```
DetailArticle.html?id=45
```
before, I navigate to : Catagory1.html -> Category 2.html -> DetailArticle.html?id=45

When I hit Back (not browser Back button) on Detail, it goes to Catagory1 instead of Category 2

**Comment by rapgithub** [comment] 2017-10-19 10:19
try using it like this <a href="/detail-article/?id=0">l-back</a>

**Comment by codetrash** [comment] 2017-10-20 02:23
@rapgithub u mean like this 
```
<!---back button-->
<div class="left sliding">
        <a href="Category2.html" class="link icon-only open-panel" data-panel="left"><i class="icon icon-bars"></i></a>
 </div>
```
yeah, right now I use it instead

**Comment by rapgithub** [comment] 2017-10-20 02:36
and the problem persist? what version of F7 you use?

**Comment by rapgithub** [comment] 2017-10-20 02:49
for linking back in history you can also use just this class="back link"

< a href="#" class="back link"> <i class="icon icon-back"></i><span>Back</span></ a>

or check mainView.router navigation methods for more methods, this link above:

https://framework7.io/docs/router-api.html

I hope you get it resolved! :)

**Comment by rapgithub** [comment] 2017-10-20 02:51
remember enable  dynamicNavbar: true in your my-app.js 

// Add view
var mainView = myApp.addView('.view-main', {
    // Because we use fixed-through navbar we can enable dynamic navbar
    dynamicNavbar: true
});

**Comment by rapgithub** [comment] 2017-10-20 02:56
and for your query when going back try to check this on that page on page init

$$(document).on('page:init', function (e) {
console.log(page.query);
});

it should print your query string to the console to see if the query is there 
good luck ! :)

**Comment by codetrash** [comment] 2017-10-20 02:59
i was using this

```
< a href="#" class="back link"> Back</ a>
```
it was no luck...so i use this instead 

```
<!---back button-->
 <div class="left sliding">
        <a href="Category2.html" class="link icon-only">
          <i class="icon icon-back"></i>
          <!-- @f7-if-ios -->
          <span>Back</span>
          <!-- @f7-endif-ios -->
       </a>
 </div>
```

but i'll check your sugesstions above

**Comment by rapgithub** [comment] 2017-10-20 03:01
check dynamicNavbar: true in my case it works fine class back link but if you need to go deeper just use better the  mainView.router navigation methods

**Comment by codetrash** [comment] 2017-10-20 03:02
yes...I set  dynamicNavbar: true already,

**Comment by rapgithub** [comment] 2017-10-20 03:09
remember this if you use the router... 

use myApp.onPageAfterAnimation

myApp.onPageAfterAnimation(pageName, callback(page)) - "callback" function will be executed after page (with "pageName" data-page attribute) animation


myApp.onPageAfterAnimation('pageName', function (page){
page.view.router.refreshPage();
page.view.router.back({
                    url: yourpage,
                    force: true,
                    ignoreCache: true
                })



});

**Comment by rapgithub** [comment] 2017-10-20 03:09
force: true,
ignoreCache: true 

is important!!

**Comment by rapgithub** [comment] 2017-10-20 03:10
myApp.onPageAfterAnimation('pageName', function (page){
page.view.router.refreshPage();
page.view.router.back({
url: yourpage,
force: true,
ignoreCache: true
})

console.log(page.query); //show your query string

});

**Comment by codetrash** [comment] 2017-10-20 03:11
great....I'll try it....

**Comment by codetrash** [comment] 2017-10-20 03:26
@rapgithub 

what do u suggest , calling Ajax inside onPageinit or onPageAfterAnimation ? 
```
app.onPageInit('detail', function (page) {
   //ajax call
    __API.detailArticle(page.query.article_id);
});
```

**Comment by codetrash** [comment] 2017-10-20 04:31
none of the above works...here i put my complete code 

```
// Dom7
var $$ = Dom7;

// isCordova helper
var isCordova = !!window.cordova;
var API_URL = 'http://localhost:90/api/article';

// Let's register Template7 helper so we can pass json string in links
Template7.registerHelper('json_stringify', function (context) {
    return JSON.stringify(context);
});

// Framework7 App main instnce
var app  = new Framework7({
    root: '#app', // App root element
    animateNavBackIcon: true, // for iOS dynamic navbar
    material: Framework7.prototype.device.ios !== true, 
    // Don't init automatically
    init: false,
    template7Pages: true,
    template7Data: {},
    swipePanel: true,
    cache:true
});

// Add main view
var mainView = app.addView('.view-main', {
    dynamicNavbar: true
});

var __API = {
    loadByCategory: function(category) {/* web service call*/},
    detailArticle: function(article_id) {/* web service call*/}
};

//Category: mobil
app.onPageInit('mobil', function (page) {
     //init loading ajax
    __API.loadByCategory('mobil');
});

//Category: Motor
app.onPageInit('motor', function (page) {
     //init loading ajax
    __API.loadByCategory('motor');
});

//detail article
app.onPageInit('detail', function (page) {
    __API.detailArticle(page.query.article_id);
});


// Init Framework7 App
if (isCordova) {
    $$(document).on('deviceready', app.init);
}
else {
    app.init();
}
```

and this  DetailArticle.html 
````
<div class="page" data-page="detail">
  <div class="navbar">
    <div class="navbar-inner">
      <div class="left sliding">
        <a href="#" class="back icon-only">
          <i class="icon icon-back"></i>
          <!-- @f7-if-ios -->
          <span>Back</span>
          <!-- @f7-endif-ios -->
        </a>
      </div>
      <div class="center sliding">Now Reading</div>
    </div>
  </div>
  <div class="page-content">
  .......
 </div>
</div>
```

**Comment by rapgithub** [comment] 2017-10-20 07:44
i will check this... what is your issue...

**Comment by codetrash** [comment] 2017-10-20 07:56
the issue is still the same
```
Navigation: Mobil -> Motor -> Detail
When I hit Back (not browser Back button) on detail, it goes to mobil instead of motor
```

**Comment by rapgithub** [comment] 2017-10-20 11:18
I will check this weekend your code but if you have some extra samples send them to me to check them out and see if i can help you

**Comment by rapgithub** [comment] 2017-10-20 19:07
checking it later or tomorrow OK take it easy 👍

**Comment by rapgithub** [comment] 2017-10-20 19:10
are you using 1.6.5?

**Comment by codetrash** [comment] 2017-10-20 21:23
yaap...im using ver 1.6.5

**Comment by rapgithub** [comment] 2017-10-20 21:30
i have tested your code and i can see that the main issue of going back is that maybe you are using the  onPageInit callback to know which page you are going back the problem with onPageInit is that if you print the page.name when going back the page.name will always be index not the previous one, dont ask me why but it is so... so you need to use for correct page the onPageAfterAnimation and onPageBeforeAnimation that will always gives you the correct page name regarding how deep you are in the router paths..

i have included here my test code with 3 pages you metioned and it works fine with query parameters as well and with on click events or inline href page references... 

I have included the console.log to print the console on every page and show you it works and in the last detail page i have created three links two with inline href links and the other with on click event...

remember when you use on click in pages deeper than index it is better to use this form below to ensure the links are clickable and works... 

$$(document).on('click', '.class-name', function (e) 

I hope this can solve your issue ! :) 

I have commented the lines below in the my-app.js because you do not need this ones but in case you want to test the myApp.onPageInit behavior you can uncomment them to see what i meant with page.name not showing the correct when going back... better use always onPageAfterAnimation and onPageBeforeAnimation for correct page names...

//myApp.onPageInit('index', function (page) {
//    console.log('app index page initialized');
//});

...

one important thing the initialization in my case i have added this

var myApp = new Framework7({
    init: false, // prevent app from automatic initialization 
    template7Pages: true, 
    force: true,
    ignoreCache: true,
    dynamicNavbar: true,
...

and at the end i initialize it like this

myApp.init();

[f7TESTE.zip](https://github.com/framework7io/Framework7/files/1403371/f7TESTE.zip)

**Comment by rapgithub** [comment] 2017-10-20 21:33
let me know if you can make it work now :) 👍

**Comment by rapgithub** [comment] 2017-10-20 21:46
remember do not use page:init to go back!!! page.name will always be index use the other methods  onPageAfterAnimation and onPageBeforeAnimation in your my-app.js

**Comment by rapgithub** [comment] 2017-10-20 22:13
i added page.query to the onPageAfterAnimation methods and the console.log show the query perfectly see this below:

  onPageAfterAnimation: function (app, page) {

        if (page.name=='index') {  
        console.log('index page onPageAfterAnimation');
        console.log(page.query); 
        }

        if (page.name=='details') {  
        console.log('details page onPageAfterAnimation');
        console.log(page.query); 
        }

        if (page.name=='motor') {       
        console.log('motor page onPageAfterAnimation');
        console.log(page.query); 
        }

    }

**Comment by rapgithub** [comment] 2017-10-21 11:19
did you resolve it? let me know so I can close this :)

**Comment by codetrash** [comment] 2017-10-21 11:37
Hi...im soory, have checked it yet.. I'll check it on Monday.... Thanks for  the help

**Comment by rapgithub** [comment] 2017-10-21 15:51
welcome!

**Comment by rapgithub** [comment] 2017-10-21 15:52
Welcome!

**Comment by nolimits4web** [comment] 2018-03-13 17:32
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Closed by nolimits4web** 2018-03-13 17:32 UTC
