### ISSUE TITLE
Please add Angular(2+) support

### ISSUE THREAD

**Issue by abuassar** [framework7io/framework7#2955] opened 2019-01-21 16:22 UTC

**Comment by nolimits4web** [comment] 2019-01-22 08:57
No chances until Angular will have JSX-compatible/compilable  template syntax

**Comment by abuassar** [comment] 2019-01-22 09:06
Ionic 4 rebuilt their components using JSX and yet they have angular/react/vue support

So there must be a way to do it.

**Comment by nolimits4web** [comment] 2019-02-19 09:32
Closing as duplicate of #2794

**Closed by nolimits4web** 2019-02-19 09:33 UTC
