### ISSUE TITLE
.desktop-XX Grid Layout Support

### ISSUE THREAD

**Issue by justadaniel** [framework7io/framework7#1638] opened 2017-06-10 22:20 UTC
This is a:
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

**DESCRIPTION**
Pretty self explanatory. It adds support for desktop screen sizes above the 1024px ranges for grid layouts.  Sometimes cards are great in tablet sizes, however when they are one laptops and above they can be quite large so being able to scale them like the example down below would be beautiful.

**EXAMPLE**
`<div class="col-100 tablet-50 desktop-25">content</div>`

**Comment by ZanderBrown** [comment] 2017-06-11 10:42
Bit out of scope but should be easy to add. @nolimits4web ?

**Comment by justadaniel** [comment] 2017-06-11 10:47
I should say 1025px since the iPad in landscape is 1024px.

**Comment by nolimits4web** [comment] 2018-03-07 14:44
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Closed by nolimits4web** 2018-03-07 14:44 UTC
