### ISSUE TITLE
Getting invalid react type error

### ISSUE THREAD

**Issue by sGaster** [framework7io/framework7#2500] opened 2018-07-12 15:33 UTC
Hello :),

I followed the react tutorial on framework7 and I always getting this strange error as soon as I want to use one of your react components. 

----------------------------------------------------------------------------
The Error:
----------------------------------------------------------------------------
`React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.`

----------------------------------------------------------------------------
Here my react version and the framework7 version which I use:
----------------------------------------------------------------------------

```
 "dependencies": {
    "@babel/runtime": "^7.0.0-beta.51",
    "framework7": "^3.0.1",
    "framework7-react": "^3.0.1",
    "meteor-node-stubs": "^0.4.1",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-meteor-data": "^0.2.11",
    "react-router-dom": "^4.3.1"
  },

```

----------------------------------------------------------------------------
Here the code:
----------------------------------------------------------------------------

```
import React, { Component } from 'react';
import Page from 'framework7-react';
 
// App component - represents the whole app
export default class App extends Component { 
  render() {

    let tPage = <Page></Page>;
    console.log(tPage);
  return (tPage); //("Hello World :).");
  }
}

```
Any idea what went wrong? Thanks in advance :).

**Comment by sGaster** [comment] 2018-07-12 15:36
Just for the sake of completing this, the error also occours when I am using your example code from the framework7 installation page:

// my-page.jsx

import React from 'react';

// Import F7 components you need
import { Page, Navbar, List, ListItem } from 'framework7-react';

export default () => (
  <Page>
    <Navbar title="My Page" />
    <List>
      <ListItem title="Item 1" />
      <ListItem title="Item 2" />
    </List>
  </Page>
);

**Comment by sGaster** [comment] 2018-07-13 08:48
More details can be found here:
http://forum.framework7.io/t/getting-invalid-react-type-error/4027/3

**Comment by 99937272** [comment] 2018-07-16 05:22
I am metting the same problem

**Comment by nolimits4web** [comment] 2018-07-16 12:49
There is something wrong with DEV setup, you can check that imports/exports are there https://github.com/framework7io/framework7/blob/master/packages/react/framework7-react.esm.js

I guess issue can be in Webpack/Babel setup which don't proceed imports/exports in f7-react source

**Comment by ffgregormueller** [comment] 2018-07-24 08:48
Also running into this issue. Sadly this makes using F7R impossible for me.. Would love to use it in our new project!

**Comment by nolimits4web** [comment] 2018-07-24 09:07
Would be good if someone who has this error will create a minimal repo with issue reproduction so we can take a look

**Comment by ffgregormueller** [comment] 2018-07-27 15:57
So here are 2 samples where F7R crashes for us. One is `create-react-app` with F7R and the other one is using GatsbyJS + F7R:
https://github.com/ffgregormueller/issues_framework7

**Comment by nolimits4web** [comment] 2018-07-27 16:09
@ffgregormueller from first look i see you have totally wrong app layout. I can't see plugin init:
```
Framework7.use(Framework7React)
```
I can't see main F7 app component (`import {App} from Framework7`). Please check the official F7 create-react app template https://github.com/framework7io/framework7-template-react

**Comment by ffgregormueller** [comment] 2018-08-07 07:14
@nolimits4web thank you for your response!
I followed the docs and stopped too soon.. _My fault!_
We recently changed our focus, so we're not using this at the moment but will look into it later on.

For me you can consider this closed, as I would reopen the issue, when there are issues again but it might be fixed by correctly setting everything up.

I would suggest, you **put some numbers on the steps in the docs** (like step 3/5), so that it is more clear that they are not finished on the layout page (https://framework7.io/react/app-layout.html) and less people would run into the issue and bother you here because of misconfigurations on their side.

**Closed** 2018-11-19 08:46 UTC
Labels: wontfix
