### ISSUE TITLE
High energy consumption of the MD theme on Safari

### ISSUE THREAD

**Issue by Pitouli** [framework7io/framework7#3550] opened 2020-02-29 23:22 UTC
When I open my app on Safari (Mac), I receive an alert saying that the tab has a "high energy consumption".

After tests, it seems to be related to the MD Theme of Framework7, since I have exactly the same issue with the kitchen sink app with MD theme, and not the one with iOS theme.

To reproduce:
- On Safari (Mac), open this: https://framework7.io/kitchen-sink/core/?theme=md
- Open the dev panel
- Go to the "Chronologies" tab (with the clock icon)
- Reload the site while recording the events
- Observe that the proc is 100% all time

Environment:
- Mac Mini OSX 10.15.3
- Safari 13.0.5 (15608.5.11)

My first analysis shows that there is an infinite loop of "style computation": you can observe the continuous pink bar (in the "disposition and rendering" line). And if you select "Disposition and rendering" in the top bar, you will have a list of millions of style re-computed over and over. 
![image](https://user-images.githubusercontent.com/542778/75616495-11a9ad80-5b52-11ea-948f-09b2dc09787e.png)
(sorry, the screenshot is in french, but the green blocks show that the proc usage is 100%, and you can observe the continuous pink line of style recomputation)

For comparison, please find below the screenshot of the iOS theme:
![image](https://user-images.githubusercontent.com/542778/75616530-7bc25280-5b52-11ea-912d-7df83114503f.png)

**Comment by nolimits4web** [comment] 2020-03-03 12:06
Closing as duplicate of #2952 (see solution there also)

**Closed by nolimits4web** 2020-03-03 12:06 UTC
