### ISSUE TITLE
Webpack hot reload forces a full refresh instead of push new content.

### ISSUE THREAD

**Issue by Taxi4you** [framework7io/framework7#3076] opened 2019-03-15 06:02 UTC
I am using F7 + React + Webpack, the project was created using the **Framework7 official CLI**, using the command: `framework7 create --ui` however I found a line in the code which ruins the HMR, in the entry file of the webpack that is the line:
`Framework7.use(Framework7React);`

As you can see, with this line I first run the code, then I comment this line, and save. From now and on, the HMR **is working**. But when I refresh the page and this line is commented (ignored) the program won't work, so I should uncomment it, save and reload, then comment again and save so HMR will work.

Is there any possibility to fix this issue?

**Comment by nolimits4web** [comment] 2019-03-15 09:19
Closing as duplicate of #3065

**Closed by nolimits4web** 2019-03-15 09:19 UTC
