### ISSUE TITLE
Infinite scroll fails to... scroll, at least at first

### ISSUE THREAD

**Issue by devgeeks** [framework7io/framework7#1720] opened 2017-08-10 01:02 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: ^1.6.4
* Platform and Target: iOS with Cordova
* Live Link or JSFiddle/Codepen: https://github.com/devgeeks/infinitescroll-bug-reproduction-demo

Above repo based on F7/Vue/Webpack template. Also includes additional instructions I will also add here.

### What you did
Added infinite scroll to the page:
```javascript
<f7-page @infinite="onInfiniteScroll" infinite-scroll
  @page:afteranimation="onPageAfterAnimation"
>
```
Then I add initial content to the page using `@page:afteranimation="onPageAfterAnimation"`

```javascript
onPageAfterAnimation () {
  // console.log('onPageAfterAnimation');
  const root = 'https://jsonplaceholder.typicode.com';
  this.$$.get(`${root}/albums/2/photos/`, {}, (data) => {
    // console.log(data);
    this.images = JSON.parse(data);
  }, (err) => {
    console.error(err);
    this.$f7.alert(error);
  });
}
```

NOTE: The `onInfiniteScroll` method is not implemented in the reproduction as it is not needed

### Expected Behavior
Once the data has loaded, the page should scroll till it gets near the bottom of the current content then fire the `onInfiniteScroll` method.

### Actual Behavior
Once the data has loaded for the page, the page is not srollable untill some other gesture (swipe to go back, etc) resets the container perhaps.

### Reproduction steps using the repro repo included above:

- build the project `npm i && npm run build`
- create a cordova app using `dist` from above
- run the app on the iOS simulator or a device
- when the app has lunched on the simulator, click the "About" link
- once the placeholder content has finished loading, try scrolling down the page
- it should fail to scroll
- now try beginning a "swipe to go back" gesture, but don't complete it and remain on this page
- now try scrolling the page
- it should scroll correctly

**Comment by nolimits4web** [comment] 2017-08-10 13:44
Pushed a fix to your repo

**Comment by devgeeks** [comment] 2017-08-10 21:25
Although this seems to fix it, it's fairly hacky (direct DOM manipulation inside two nested setTimeouts). I might use it as the basis to find a nicer work around if I can.

I wonder if it will be possible to make it part of the infinite scroll itself since it only seems to occur with it not with normally scrolled pages?

**Comment by nolimits4web** [comment] 2018-03-07 14:53
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Closed by nolimits4web** 2018-03-07 14:53 UTC
