### ISSUE TITLE
Custom Search with autocomplete and dropdown not work on Android device

### ISSUE THREAD

**Issue by contfedorov** [framework7io/framework7#3890] opened 2021-05-14 12:54 UTC
* Framework7 version: 5.7.13
* Platform and Target: Android Device (tested via Nexus 6P w/ Android 8.1.0), Android Simulator (tested via Android 11)
* Live Link or JSFiddle: https://jsfiddle.net/forallepsilon/Lgz6hmpk/ 

### Describe the bug

I have page containing:
- Searchbar with `customSearch: true`
- Dropdown with Ajax-Data loading
- Custom `dropdownContainerEl`

Looks like everything is implemented according to [sample provided in docs](https://v5.framework7.io/docs/autocomplete.html)  (section "Dropdown With Ajax-Data").

I expect that my request to REST API is executed while I type, and results are rendered in dropdown. It works in desktop Chrome, iOS device and simulator, but do not work on Android device. In latter case, dropdown does not appear.

After some debugging, it seems like an issue inside F7, but I can not say that for sure.

### To Reproduce
1. Clone this sample repo: https://github.com/contfedorov/f7-issues/tree/android_search_suggest/
2. Run app on Android device: `cordova prepare android && cordova run android` ([Cordova CLI](https://www.npmjs.com/package/cordova) must be installed)
3. Open app and tap search icon
4. Start typing "er" to trigger API call. "Ervin Howell" and "Glenna Reichert" should be the results. They will be shown on iOS/Chrome, but not on Android device

### Expected behavior
Search results are displayed in dropdown right under search bar

### Actual Behavior
No dropdown is displayed

### Screenshots
In both cases API request is performed correctly, but result is not rendered on Android.

Screen from iOS 14.5 simulator:
![f7-search-dropdown-ios](https://user-images.githubusercontent.com/8971835/118273289-f70ceb80-b4ed-11eb-91a0-cbad4bc3bb95.png)

Screen from Android 11 simulator:
![f7-search-dropdown-android](https://user-images.githubusercontent.com/8971835/118273283-f4aa9180-b4ed-11eb-85c4-e49a86ee4540.png)

### Additional context
This code works perfectly on desktop Chrome, iOS device and simulator. Only Android device causes problems.

**Comment by boosh** [comment] 2021-07-02 15:49
I have the same issue. Did you find a fix?

**Comment by contfedorov** [comment] 2021-07-02 16:07
@boosh 
Yes, I've just open autocomplete manually when needed. Namely, when I receive response from web api call, I do the following:

```js
autocomplete.preloaderHide();
render(responseResult);
autocomplete.open();
```

**Comment by boosh** [comment] 2021-07-02 16:10
Thanks. I'll try that approach if I can't fix this.

**Comment by boosh** [comment] 2021-07-04 11:27
I got this working in the end, but I can't really say how. I think it was because I was using a nullable object. Either way, I can confirm the latest autocomplete does work on Android (Pixel 3a XL API 30 emulator).

```
    "framework7": "^6.0.22",
    "framework7-icons": "^4.0.2",
    "framework7-vue": "^6.0.22",
```

**Comment by contfedorov** [comment] 2021-07-04 12:44
@boosh 
Well, I've checked F7 v5 only. Did you try this version? Or v6 only?

**Comment by boosh** [comment] 2021-07-05 06:27
I've only checked v6. So it looks like the issue is fixed now.

**Closed** 2022-05-02 07:26 UTC
Labels: wontfix
